import tkinter
class Book:
    def __init__(self,master):
        self.master=master
        master.title("books")
        self.jenrelabel=tkinter.Label(master,text="janr book")
        self.jenrelabel.grid(row=0,column=0)
        self.comedivar=tkinter.BooleanVar()
        self.comedi=tkinter.Checkbutton(master,text="comedi",variable=self.comedivar)
        self.comedi.grid(row=1,column=0)
        self.fantasivar=tkinter.BooleanVar()
        self.fentasi=tkinter.Checkbutton(master,text="fentasi",variable=self.fantasivar)
        self.fentasi.grid(row=2,column=0)
        self.romenticvar=tkinter.BooleanVar()
        self.romentic=tkinter.Checkbutton(master,text="romantic",variable=self.romenticvar)
        self.romentic.grid(row=3,column=0)
        self.horrorvar=tkinter.BooleanVar()
        self.horror=tkinter.Checkbutton(master,text="horror",variable=self.horrorvar)
        self.horror.grid(row=4,column=0)
        self.detectivvar=tkinter.BooleanVar()
        self.detectiv=tkinter.Checkbutton(master,text="detectiv",variable=self.detectivvar)
        self.detectiv.grid(row=0,column=1)
        self.comicsvar=tkinter.BooleanVar()
        self.comics=tkinter.Checkbutton(master,text="comics",variable=self.comicsvar)
        self.comics.grid(row=1,column=1)
        self.colorlabl=tkinter.Label (master,text="cus color")
        self.colorlabl.grid(row=2,column=1)
        self.bluevar=tkinter.BooleanVar()
        self.blue=tkinter.Checkbutton(master,text="blue",variable=self.bluevar)
        self.blue.grid(row=3,column=1)
        self.redvar=tkinter.BooleanVar()
        self.red=tkinter.Checkbutton(master,text="red",variable=self.redvar)
        self.red.grid(row=4,column=1)
        self.greanvar=tkinter.BooleanVar()
        self.grean=tkinter.Checkbutton(master,text="grean",variable=self.greanvar)
        self.grean.grid(row=0,column=2)
        self.purplevar=tkinter.BooleanVar()
        self.purple=tkinter.Checkbutton(master,text="purple",variable=self.purplevar)
        self.purple.grid(row=1,column=2)
        self.delivari=tkinter.StringVar()
        self.delivari.set("kurer")
        self.menu=tkinter.OptionMenu(master,self.delivari,"kurer","pikap")
        self.menu.grid(row=3,column=2)
        self.menuleble=tkinter.Label(master,text="coos deliweri")
        self.menuleble.grid(row=2,column=2)
        self.namelable=tkinter.Label(master,text="enter name")
        self.namelable.grid(row=5,column=0)
        self.name=tkinter.Entry(master)
        self.name.grid(row=6,column=0)
        self.surnamelabel=tkinter.Label(master,text="enter surname")
        self.surnamelabel.grid(row=5,column=1)
        self.surname=tkinter.Entry(master)
        self.surname.grid(row=6,column=1)
        self.adreslabel=tkinter.Label(master,text="enter adres")
        self.adreslabel.grid(row=7,column=0)
        self.adres=tkinter.Entry(master)
        self.adres.grid(row=8,column=0)
        self.fonlable=tkinter.Label(master,text="enter fon namber")
        self.fonlable.grid(row=7,column=1)
        self.fon=tkinter.Entry(master)
        self.fon.grid(row=8,column=1)
        self.sabmit=tkinter.Button(master,text="sabmit",command=self.info())
        self.sabmit.grid(row=8,column=2)
    def info(self):
        janr=[]
        if self.comedivar.get():
            janr.append("comedi")
        if self.fantasivar.get():
            janr.append("fentasi")
        if self.romenticvar.get():
            janr.append("romentik")
        if self.horrorvar. get():
            janr.append("horor")
        if self.comicsvar.get():
            janr.append("comics")
        if self.detectivvar.get():
            janr.append("detectiv")
        colors=[]
        if self.bluevar.get():
            colors.append("blue")
        if self.redvar.get():
            colors.append("red")
        if self.greanvar.get():
            colors.append("graen")
        if self.purplevar.get():
            colors.append("purpel")
        deliweri=self.delivari.get()
        name=self.name.get()
        surlname=self.surname.get()
        adres=self.adres.get()
        fon=self.fon.get()
        print("information")
        print("janr:",janr)
        print("colors",colors)
        print("deliweri",deliweri)
        print('name',name)
        print("surlname",surlname)
        print("adres",adres)
        print("fon",fon)

top=tkinter.Tk()
app=Book(top)
top.mainloop()