ololo=["sana","oleg","wana"]
print(ololo)

ololo.append('tyytyty')
print(ololo)
ololo.remove("tyytyty")
print(ololo)
ololo.sort()
print(ololo)
ololo.reverse()
print(ololo)
ololo.extend(["melege","jjhhggf"])
print(ololo)
ololo.insert(3,"oleg")
print(ololo)
ololo.clear()
print(ololo)