import random
import turtle
t=turtle.Pen()
turtle.bgcolor("red")
turtle.hideturtle()
def tototo(x,y):
    t.pencolor("green")
    t.fillcolor("green")
    t.penup()
    t.setpos(x,y)
    t.pendown()
    t.begin_fill()
    t.circle(59)
    t.end_fill()
    t.setpos(x-15,y+60)
    t.pencolor("green")
    t.fillcolor("black")
    t.begin_fill()
    t.circle(10)
    t.end_fill()
    t.setpos(x+15, y+60)
    t.begin_fill()
    t.circle(10)
    t. end_fill()
    t.setpos(x-25,y+40)
    t.pencolor("black")
    t.width(10)
    t.goto(x-10,y+20)
    t.goto(x+10,y+20)
    t.goto(x+25,y+4n0)
    t.width(1)
for m in range(50):
    x=random.randrange(-turtle.window_width()//2,turtle.window_width()//2)
    y=random.randrange(-turtle.window_height()//2,turtle.window_height()//2)
    tototo(x,y)